import { useEffect, useRef, useState } from 'react';
import type { Guide, GuideNode, Session, Transition } from './engine';
import { validateGuide, newSession, getStates, complete, previewTransition, applyTransition, undo, serialize, restore, isFinished } from './engine';
import { meetup, bookSwap, blankGuide } from './samples';
import { readSaved, writeSaved, clearSaved } from './storage';

type Workspace = {guide: Guide; session: Session};
const labels: Record<string,string> = {'unresolved-condition':'Choice needed','inactive-by-choice':'Not needed','blocked-by-prerequisite':'Waiting','available':'Ready','done':'Complete'};
export default function App() {
 const [workspace,setWorkspace] = useState<Workspace|null>(null);
 const [draft,setDraft] = useState<Guide|null>(null);
 const [view,setView] = useState<'home'|'edit'|'preview'|'run'>('home');
 const [pendingStart,setPendingStart] = useState<{guide:Guide;edit:boolean}|null>(null);
 const [pending,setPending] = useState<Transition|null>(null);
 const [notice,setNotice] = useState(''); const [saveStatus,setSaveStatus] = useState('Local to this browser');
 const [recovery,setRecovery] = useState(''); const [loaded,setLoaded] = useState(false);
 const [selected,setSelected] = useState(''); const [clearConfirm,setClearConfirm] = useState(false);
 const startRef=useRef<HTMLDialogElement>(null); const nextRef=useRef<HTMLHeadingElement>(null);
 const dialogRef=useRef<HTMLDialogElement>(null); const clearRef=useRef<HTMLDialogElement>(null);
 const headingRef=useRef<HTMLHeadingElement>(null); const sourceRef=useRef<HTMLTextAreaElement>(null);
 const saveQueue=useRef(Promise.resolve());
 useEffect(()=>{readSaved().then(raw=>{if(raw!==undefined){const result=restore(typeof raw==='string'?raw:'invalid');if(result.ok){setWorkspace({guide:result.guide,session:result.session});setView('run');setNotice('Your saved place is restored. Review your choices and continue.');}else setRecovery(result.error);}}).catch(()=>setRecovery('Browser storage could not be opened. You can continue, but your place may not be saved.')).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(!loaded||!workspace)return;setSaveStatus('Saving on this device…');saveQueue.current=saveQueue.current.catch(()=>{}).then(()=>writeSaved(serialize(workspace.guide,workspace.session))).then(()=>setSaveStatus('Saved on this device')).catch(()=>setSaveStatus('Not saved. Browser storage is unavailable.'));},[workspace,loaded]);
 useEffect(()=>{if(pending){dialogRef.current?.showModal();}else dialogRef.current?.close();},[pending]);
 useEffect(()=>{if(clearConfirm)clearRef.current?.showModal();else clearRef.current?.close();},[clearConfirm]);
 useEffect(()=>{headingRef.current?.focus();},[view]);
 useEffect(()=>{if(pendingStart)startRef.current?.showModal();else startRef.current?.close();},[pendingStart]);
 function acceptWorkspace(next:Workspace){serialize(next.guide,next.session);setWorkspace(next);}
 function chooseStart(guide:Guide,edit=false){if(workspace)setPendingStart({guide,edit});else start(guide,edit);}
 function start(guide:Guide,edit=false){try{if(!(edit&&guide.nodes.length===0))acceptWorkspace({guide,session:newSession(guide)});setRecovery('');setDraft(structuredClone(guide));setView(edit?'edit':'run');setSelected('');setNotice(edit?'Draft changes are not saved until you preview and run the guide.':'A fresh guide is ready. Choices start unanswered.');}catch(e){setNotice(String(e));}}
 function request(t:Transition){if(!workspace||(t.type==='edit'&&t.guide.id!==workspace.guide.id)){if(t.type==='edit')start(t.guide);return;}setPending(t);}
 function confirm(){if(!workspace||!pending)return;try{const result=applyTransition(workspace.guide,workspace.session,pending);acceptWorkspace(result);setNotice(previewTransition(workspace.guide,workspace.session,pending).reason);if(pending.type==='edit')setView('run');setPending(null);}catch(e){setPending(null);setNotice(String(e));}}
 function editNode(id:string,change:Partial<GuideNode>){if(draft)setDraft({...draft,nodes:draft.nodes.map(n=>n.id===id?{...n,...change}:n)});}
 function addNode(type:'action'|'decision'){if(!draft)return;const id=crypto.randomUUID();setDraft({...draft,nodes:[...draft.nodes,{id,type,text:'',prerequisites:[]}]});setSelected(id);}
 function useSelection(){if(!draft||!selected||!sourceRef.current)return;const {selectionStart:start,selectionEnd:end}=sourceRef.current;if(start===end){setNotice('Select a passage in the original instructions first.');return;}editNode(selected,{text:draft.source.slice(start,end),source:{start,end}});setNotice('Exact selected wording linked to this step.');}
 const guide=workspace?.guide; const states=workspace?getStates(workspace.guide,workspace.session):{};
 const available=guide?.nodes.filter(n=>states[n.id]?.state==='available')??[];
 const done=guide?.nodes.filter(n=>states[n.id]?.state==='done')??[];
 const inactive=guide?.nodes.filter(n=>states[n.id]?.state==='inactive-by-choice')??[];
 const activeNode=available.find(n=>n.id===selected)??available.find(n=>n.type==='action')??available[0];
 const errors=draft?validateGuide(draft):[];
 const scope=pending&&workspace?previewTransition(workspace.guide,workspace.session,pending):null;
 const lastCompleted=workspace?[...workspace.session.history].reverse().find(e=>e.event.type==='complete'&&workspace.session.completed.includes(e.event.nodeId)):undefined;
 const lastCompletedId=lastCompleted?.event.type==='complete'?lastCompleted.event.nodeId:null;
 const lastReset=(id:string)=>workspace?[...workspace.session.history].reverse().find(e=>e.reset.includes(id))?.reason:undefined;
 const nodeName=(id:string)=>guide?.nodes.find(n=>n.id===id)?.text||id;
 return <><a className="skip" href="#main">Skip to main content</a><header className="topbar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setView('home');}} aria-label="ResumeHere home"><span className="brand-icon" aria-hidden="true">↳</span>Resume<span>Here</span><span className="beta">PROTOTYPE</span></a><div className="local"><span aria-hidden="true">◉</span> {saveStatus}</div></header>
 <main id="main"><div className="announcement" role="status" aria-live="polite">{notice}</div>
 {recovery&&<section className="recovery"><h2>We couldn’t safely restore your place</h2><p>{recovery}</p><p>No saved completion has been applied. Start a sample or create a guide to replace this snapshot.</p></section>}
 {!loaded?<p>Opening your local workspace…</p>:view==='home'?<>
 <section className="hero"><div><p className="eyebrow">A PLACE TO PICK UP AGAIN</p><h1 ref={headingRef} tabIndex={-1}>Plans change.<br/>Your place stays clear.</h1><p className="intro">Turn instructions into a guide you can follow. Pause, come back, or change a choice. See exactly what’s next, and what still counts.</p><div className="button-row"><button className="primary" onClick={()=>chooseStart(meetup)}>Try the meetup guide <span aria-hidden="true">↗</span></button><button onClick={()=>chooseStart(blankGuide(),true)}>Create a guide</button></div>{workspace&&<button className="text-button" onClick={()=>setView('run')}>Return to “{workspace.guide.title}” →</button>}<p className="quiet">No account. No AI. Your instructions stay in this browser.</p></div><div className="hero-art" aria-label="A conceptual illustration of progress retained when a choice changes"><div className="paper-label">SMALL STEPS. A CLEAR RETURN.</div><div className="art-step"><span>✓</span><div>Pack a notebook<small>Still complete</small></div></div><div className="route-line"/><div className="art-choice">Reserved a kit? <b>Yes → No</b></div><div className="route-line"/><div className="art-step amber"><span>↻</span><div>Pick up an activity sheet<small>Ready for your new choice</small></div></div><div className="art-note">A changed choice.<br/>Not a blank slate.</div></div></section>
 <section className="home-bottom"><div><p className="eyebrow">HOW IT WORKS</p><h2>Less finding your place.<br/>More moving forward.</h2></div><ol className="three-up"><li><b>01 / Make it yours</b><p>Keep the original wording. Connect actions and yes/no choices yourself.</p></li><li><b>02 / Follow at your pace</b><p>See what’s ready, what’s waiting, and why. Progress saves locally.</p></li><li><b>03 / Change with clarity</b><p>Preview affected steps before a reset. Keep independent work. Undo a change.</p></li></ol></section><section className="sample-strip"><div><strong>Another small adventure</strong><p>A fictional neighborhood book swap. Six steps, one choice.</p></div><button onClick={()=>chooseStart(bookSwap)}>Try book swap →</button></section></>:view==='edit'&&draft?<>
 <section className="page-heading"><div><p className="eyebrow">BUILD YOUR GUIDE</p><h1 ref={headingRef} tabIndex={-1}>Keep the words. Add a path.</h1><p>Nothing is interpreted automatically. Draft changes are saved only when you preview and run.</p></div><button onClick={()=>setView(workspace?'run':'home')}>Cancel editing</button></section>
 <div className="editor-layout"><section className="panel source-editor"><label htmlFor="guide-title">Guide title</label><input id="guide-title" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><label htmlFor="source">Original instructions</label><p id="source-help" className="quiet">Paste low-stakes instructions. Select a passage, then link it to the selected step. Editing this whole text resets all progress.</p><textarea id="source" ref={sourceRef} aria-describedby="source-help" value={draft.source} rows={14} onChange={e=>setDraft({...draft,source:e.target.value,nodes:draft.nodes.map(n=>({...n,source:undefined}))})}/><button disabled={!selected} onClick={useSelection}>Use selection for selected step</button><p className="quiet">Exact text and character positions are preserved. Source text is never executed.</p></section>
 <section><div className="section-top"><h2>Your steps <span className="count">{draft.nodes.length}/16</span></h2><div className="button-row"><button disabled={draft.nodes.filter(n=>n.type==='action').length>=12} onClick={()=>addNode('action')}>+ Action</button><button disabled={draft.nodes.filter(n=>n.type==='decision').length>=4} onClick={()=>addNode('decision')}>+ Choice</button></div></div>{!draft.nodes.length&&<div className="empty-state"><h3>Start with one clear action</h3><p>Add an action, then type its instructions or link an exact source passage.</p></div>}
 {draft.nodes.map((n,index)=><section className={'editor-node panel '+(selected===n.id?'selected':'')} key={n.id} onFocus={()=>setSelected(n.id)}><div className="section-top"><h3>{index+1}. {n.type==='decision'?'Yes/no choice':'Action'}</h3><button className="small" onClick={()=>setDraft({...draft,nodes:draft.nodes.filter(x=>x.id!==n.id)})}>Remove<span className="sr-only"> step {index+1}</span></button></div><label htmlFor={'text-'+n.id}>{n.type==='decision'?'Question':'Exact instructions'}</label><textarea id={'text-'+n.id} aria-invalid={errors.some(e=>e.nodeId===n.id&&e.field==='text')} aria-describedby={errors.some(e=>e.nodeId===n.id)?'error-'+n.id:undefined} value={n.text} rows={2} onChange={e=>editNode(n.id,{text:e.target.value,source:undefined})}/>{errors.some(e=>e.nodeId===n.id)&&<ul id={'error-'+n.id} className="field-errors">{errors.filter(e=>e.nodeId===n.id).map((e,i)=><li key={i}>{e.message}</li>)}</ul>}{n.source&&<p className="source-tag">Linked source: characters {n.source.start}–{n.source.end}</p>}{n.type==='action'&&<><fieldset><legend>Wait for these steps</legend>{draft.nodes.filter(x=>x.id!==n.id).map(x=><label className="check-label" key={x.id}><input type="checkbox" checked={n.prerequisites.includes(x.id)} onChange={e=>editNode(n.id,{prerequisites:e.target.checked?[...n.prerequisites,x.id]:n.prerequisites.filter(id=>id!==x.id)})}/>{x.text||'Untitled '+x.type}</label>)}</fieldset><label htmlFor={'gate-'+n.id}>Only needed when</label><select id={'gate-'+n.id} value={n.condition?.decisionId??''} onChange={e=>editNode(n.id,{condition:e.target.value?{decisionId:e.target.value,answer:'yes'}:undefined})}><option value="">Always needed</option>{draft.nodes.filter(x=>x.type==='decision').map(x=><option key={x.id} value={x.id}>{x.text||'Untitled choice'}</option>)}</select>{n.condition&&<label className="inline-label">Answer<select aria-label={'Required answer for step '+(index+1)} value={n.condition.answer} onChange={e=>editNode(n.id,{condition:{...n.condition!,answer:e.target.value as 'yes'|'no'}})}><option value="yes">Yes</option><option value="no">No</option></select></label>}</>}</section>)}
 <div className="panel validation">{errors.length?<><h3>Fix these before running</h3><ul>{errors.map((e,i)=><li key={i}>{e.nodeId?'Step '+(draft.nodes.findIndex(n=>n.id===e.nodeId)+1)+' · ':''}{e.field}: {e.message}</li>)}</ul></>:<p>✓ Connections are valid. Ready to preview.</p>}<button className="primary" disabled={errors.length>0} onClick={()=>setView('preview')}>Preview guide →</button></div></section></div></>:view==='preview'&&draft?<><section className="page-heading"><div><p className="eyebrow">REVIEW BEFORE RUNNING</p><h1 ref={headingRef} tabIndex={-1}>{draft.title}</h1><p>{draft.nodes.filter(n=>n.type==='action').length} actions · {draft.nodes.filter(n=>n.type==='decision').length} choices</p></div><button onClick={()=>setView('edit')}>Back to editor</button></section><section className="panel"><ol className="preview-list">{draft.nodes.map(n=><li key={n.id}><strong>{n.text}</strong><p>{n.type==='decision'?'You answer Yes, No, or leave unknown.':n.condition?`Needed when “${draft.nodes.find(x=>x.id===n.condition!.decisionId)?.text}” = ${n.condition.answer}`:'Always needed'}{n.prerequisites.length>0&&' · Waits for '+n.prerequisites.map(id=>draft.nodes.find(x=>x.id===id)?.text).join('; ')}</p></li>)}</ol><button className="primary" onClick={()=>request({type:'edit',guide:draft})}>Review changes & run</button></section></>:workspace&&guide?<>
 <section className="page-heading"><div><p className="eyebrow">YOUR PLACE, AT A GLANCE</p><h1 ref={headingRef} tabIndex={-1}>{guide.title}</h1><p>{guide.id.startsWith('fictional')?'Fictional demonstration sample. ':''}Take the next step when you’re ready.</p></div><button onClick={()=>{setDraft(structuredClone(guide));setView('edit');}}>Edit instructions</button></section>
 <div className="run-layout"><div className="run-main"><section className="resume-strip"><div><span className="eyebrow">PROGRESS</span><strong>{done.filter(n=>n.type==='action').length} of {guide.nodes.filter(n=>n.type==='action').length} actions complete</strong><p>{inactive.length} not needed · {available.length} ready now</p>{lastCompletedId&&<p className="last-completed">Last completed: {nodeName(lastCompletedId)}</p>}</div><div className="progress-track" aria-hidden="true"><i style={{width:((done.length+inactive.length)/guide.nodes.length*100)+'%'}}/></div></section>
 {isFinished(guide,workspace.session)?<section className="next-card finished"><p className="eyebrow">YOU’VE REACHED THE END</p><h2 ref={headingRef} tabIndex={-1}>A clear place to finish.</h2><p>Every required step is complete. Steps excluded by your choices are marked “Not needed,” never complete.</p></section>:activeNode?<section className="next-card"><div className="section-top"><p className="eyebrow">{activeNode.type==='decision'?'A CHOICE TO MAKE':'READY WHEN YOU ARE'}</p><span className="pill">{activeNode.type==='decision'?'Choice':'Next action'}</span></div><h2 ref={nextRef} tabIndex={-1}>{activeNode.text}</h2><p className="next-reason">{states[activeNode.id].reason}</p>{activeNode.type==='action'?<button className="primary" onClick={()=>{try{acceptWorkspace({...workspace,session:complete(guide,workspace.session,activeNode.id)});setNotice('Completed: '+activeNode.text);setSelected('');requestAnimationFrame(()=>(nextRef.current??headingRef.current)?.focus());}catch(e){setNotice(String(e));}}}>Mark complete <span aria-hidden="true">✓</span></button>:<p>Answer this choice in “Your choices” below.</p>}{activeNode.source&&<details><summary>See original wording</summary><blockquote>{guide.source.slice(activeNode.source.start,activeNode.source.end)}</blockquote><p className="quiet">Exact passage, characters {activeNode.source.start}–{activeNode.source.end}.</p></details>}</section>:<section className="next-card"><h2>One choice before the next step.</h2><p>Review unanswered choices below. Unknown answers never count as “No.”</p></section>}
 {available.filter(n=>n.type==='action').length>1&&<section className="alternatives"><h3>Or choose another ready action</h3>{available.filter(n=>n.type==='action'&&n.id!==activeNode?.id).map(n=><button key={n.id} onClick={()=>setSelected(n.id)}>{n.text} <span aria-hidden="true">→</span></button>)}</section>}
 <section className="choices panel"><h2>Your choices</h2><p className="quiet">You decide. Changing an answer previews the progress that needs redoing.</p>{guide.nodes.filter(n=>n.type==='decision').map(n=><fieldset key={n.id}><legend>{n.text}</legend><div className="choice-buttons">{(['yes','no',null] as const).map(answer=><button key={answer??'unknown'} aria-pressed={(workspace.session.answers[n.id]??null)===answer} onClick={()=>request({type:'answer',nodeId:n.id,answer})}>{answer===null?'Unknown':answer==='yes'?'Yes':'No'}</button>)}</div></fieldset>)}{!guide.nodes.some(n=>n.type==='decision')&&<p>This guide has no choices.</p>}</section>
 <details className="panel original"><summary>Original instructions</summary><p className="literal">{guide.source||'No source document supplied.'}</p></details></div>
 <aside className="journey panel"><div className="section-top"><h2>The whole path</h2><span aria-hidden="true">↳</span></div><p className="quiet">Your progress, with a reason for every state.</p><ol>{guide.nodes.map((n,i)=><li key={n.id} className={'state-'+states[n.id].state}><span className="step-marker" aria-hidden="true">{states[n.id].state==='done'?'✓':states[n.id].state==='inactive-by-choice'?'—':i+1}</span><div><strong>{n.text}</strong><span className="state-label">{labels[states[n.id].state]}</span><details><summary>Why this state?</summary><p>{states[n.id].reason}</p>{lastReset(n.id)&&<p>Most recent reset: {lastReset(n.id)}</p>}</details>{n.type==='action'&&states[n.id].state==='done'&&<button className="text-button" onClick={()=>request({type:'uncomplete',nodeId:n.id})}>Undo completion</button>}</div></li>)}</ol><button disabled={!workspace.session.history.length} onClick={()=>{try{acceptWorkspace(undo(guide,workspace.session));setNotice('Restored the complete previous guide and progress state.');}catch(e){setNotice(String(e));}}}>Undo last transition</button><p className="quiet">Undo restores the full previous state, including edits.</p></aside></div>
 <section className="privacy-row"><p><strong>Only on this device.</strong> Saved in this browser, without encryption. Anyone using this browser profile may see it. Avoid sensitive instructions.</p><button className="small" onClick={()=>setClearConfirm(true)}>Clear saved guide</button></section></>:null}
 </main><footer><span className="brand-text">ResumeHere</span><p>Designed to support reorientation. No measured accessibility benefit claimed.</p><span>Inclusive Technology · Original prototype</span></footer>
 <dialog ref={dialogRef} onCancel={()=>setPending(null)} aria-labelledby="change-title"><div className="dialog-content"><p className="eyebrow">A CHANGE, WITH A CLEAR SCOPE</p><h2 id="change-title">Review before continuing</h2><p>{scope?.reason}</p><h3>Completed steps to reset ({scope?.reset.length??0})</h3>{scope?.reset.length?<ul>{scope.reset.map(id=><li key={id}>{nodeName(id)}</li>)}</ul>:<p>No completed steps need resetting.</p>}<h3>Still complete ({scope?.retained.length??0})</h3>{scope?.retained.length?<ul>{scope.retained.map(id=><li key={id}>{nodeName(id)}</li>)}</ul>:<p>No other completed steps to retain.</p>}<details><summary>All affected steps ({scope?.affected.length??0})</summary><ul>{scope?.affected.map(id=><li key={id}>{nodeName(id)}</li>)}</ul></details><p className="quiet">You can undo this whole transition afterwards. Changing an answer back does not restore stale checks.</p><div className="button-row"><button autoFocus onClick={()=>setPending(null)}>Cancel</button><button className="primary" onClick={confirm}>Confirm change</button></div></div></dialog>
 <dialog ref={startRef} onCancel={()=>setPendingStart(null)} aria-labelledby="start-title"><div className="dialog-content"><h2 id="start-title">Start a fresh guide?</h2><p>This replaces your current saved guide and its progress in this browser. A blank guide is saved only after you preview and run it. You cannot undo this replacement.</p><div className="button-row"><button autoFocus onClick={()=>setPendingStart(null)}>Keep current guide</button><button className="primary" onClick={()=>{if(pendingStart)start(pendingStart.guide,pendingStart.edit);setPendingStart(null);}}>Start fresh</button></div></div></dialog>
 <dialog ref={clearRef} onCancel={()=>setClearConfirm(false)} aria-labelledby="clear-title"><div className="dialog-content"><h2 id="clear-title">Clear this saved guide?</h2><p>This removes the guide, answers, progress, and undo history from ResumeHere. It does not clear other browser data. This cannot be undone.</p><div className="button-row"><button autoFocus onClick={()=>setClearConfirm(false)}>Keep my guide</button><button className="danger" onClick={async()=>{try{await saveQueue.current;await clearSaved();setWorkspace(null);setDraft(null);setView('home');setClearConfirm(false);setRecovery('');setSaveStatus('Local to this browser');setNotice('This guide and its progress have been cleared.');}catch{setNotice('Could not clear saved data. Please try again.');}}}>Clear guide & progress</button></div></div></dialog>
 </>;
}
